// <auto-generated />
using System;
using CurrencyExchange.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurrencyExchange.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CurrencyExchangeDbContext))]
    partial class CurrencyExchangeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurrencyExchange.Domain.Models.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("df732d6b-34c3-4322-a75d-b946f5835e6f"),
                            CurrencyCode = "DKK",
                            DisplayName = "Danish krone"
                        },
                        new
                        {
                            Id = new Guid("dd4ce93c-e72b-4000-ac54-9c2fc459d4c1"),
                            CurrencyCode = "EUR",
                            DisplayName = "Euro"
                        },
                        new
                        {
                            Id = new Guid("227c7742-7189-4320-b1a1-baefdf76bda9"),
                            CurrencyCode = "USD",
                            DisplayName = "United States dollar"
                        },
                        new
                        {
                            Id = new Guid("44c0f848-1a58-449f-9f11-7978204a831f"),
                            CurrencyCode = "GBP",
                            DisplayName = "Pound sterling"
                        },
                        new
                        {
                            Id = new Guid("4fdc8575-c76c-45c5-bdf3-cbdea54ee781"),
                            CurrencyCode = "SEK",
                            DisplayName = "Swedish krona"
                        },
                        new
                        {
                            Id = new Guid("61400521-7945-41f9-99db-c5f9ffd3c4d7"),
                            CurrencyCode = "NOK",
                            DisplayName = "Norwegian krone"
                        },
                        new
                        {
                            Id = new Guid("8ba142c0-f452-42c3-849d-de409f099951"),
                            CurrencyCode = "CHF",
                            DisplayName = "Swiss franc"
                        },
                        new
                        {
                            Id = new Guid("84878f30-8af2-420b-b6e5-fb5be2059039"),
                            CurrencyCode = "JPY",
                            DisplayName = "Japanese yen"
                        },
                        new
                        {
                            Id = new Guid("b26f0b71-b5ff-4239-a01b-31add647c4bf"),
                            CurrencyCode = "LTU",
                            DisplayName = "Lithuanian litas"
                        });
                });

            modelBuilder.Entity("CurrencyExchange.Domain.Models.CurrencyRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MainCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("MoneyCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("MainCurrency");

                    b.HasIndex("MoneyCurrency");

                    b.ToTable("CurrencyRates", null, t =>
                        {
                            t.HasCheckConstraint("CK_CurrencyRates_Rate_Positive", "[Rate] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("5eebddfe-a5c6-4b25-916d-0a7609667f7e"),
                            MainCurrency = "EUR",
                            MoneyCurrency = "DKK",
                            Rate = 7.4394m
                        },
                        new
                        {
                            Id = new Guid("b2636d1a-f60c-4294-9b23-12c32f075c5c"),
                            MainCurrency = "USD",
                            MoneyCurrency = "DKK",
                            Rate = 6.6311m
                        },
                        new
                        {
                            Id = new Guid("773135cd-a1b3-4f03-b1ab-e38d5253943e"),
                            MainCurrency = "GBP",
                            MoneyCurrency = "DKK",
                            Rate = 8.5285m
                        },
                        new
                        {
                            Id = new Guid("97a2ed34-b0ab-45be-a7c2-c365ebc6adbb"),
                            MainCurrency = "SEK",
                            MoneyCurrency = "DKK",
                            Rate = 0.7610m
                        },
                        new
                        {
                            Id = new Guid("a8764ce9-7a57-4e61-815d-d74d1fbe891a"),
                            MainCurrency = "NOK",
                            MoneyCurrency = "DKK",
                            Rate = 0.7840m
                        },
                        new
                        {
                            Id = new Guid("b85f11fe-cd8f-4f88-b436-b56920a0dfed"),
                            MainCurrency = "CHF",
                            MoneyCurrency = "DKK",
                            Rate = 6.8358m
                        },
                        new
                        {
                            Id = new Guid("c1d567e5-8445-4eb5-89fe-066f34ae7bf0"),
                            MainCurrency = "JPY",
                            MoneyCurrency = "DKK",
                            Rate = 0.059740m
                        },
                        new
                        {
                            Id = new Guid("7e3c6e84-662b-44ff-90dc-553e445bd39b"),
                            MainCurrency = "LTU",
                            MoneyCurrency = "JPY",
                            Rate = 3.4528m
                        });
                });

            modelBuilder.Entity("CurrencyExchange.Domain.Models.CurrencyRate", b =>
                {
                    b.HasOne("CurrencyExchange.Domain.Models.Currency", null)
                        .WithMany()
                        .HasForeignKey("MainCurrency")
                        .HasPrincipalKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurrencyExchange.Domain.Models.Currency", null)
                        .WithMany()
                        .HasForeignKey("MoneyCurrency")
                        .HasPrincipalKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
